#include "CM-ARM7.H"

int main()
{
  INITIALIZE_MODULE(LCD_DISPLAY);
  DISPLAY_MESSAGE  (FIRST_LINE, " CHIPMAX DESIGN ");
  DISPLAY_MESSAGE  (SECOND_LINE,"0123456789ABCDEF");
  SHIFT_MESSAGE    (LEFT,500);		
}

